version: "3"

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: q
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
    restart: always
    depends_on:
      - mongo-db
    links:
      - mongo-db
    networks:
      - app-network

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: workrosterapp
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    environment:
      MONGO_URI: workrosterapp
      NODE_ENV: production
      JWT_SECRET: bobisuruncle
    depends_on:
      - mongo-db
    ports:
      - "3002:3002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data_container:
