version: "3"

services:
  client:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/frontend/src
    ports:
      - "3000:3000"
  server:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/backend/src
    ports:
      - "3001:3001"
  mongodb:
    image: mongo
    container_name: "mongo"
    ports:
      - "3002:3002"
