version: "3"

services:
  server:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017
      JWT_SECRET: bobisuruncle
    networks:
      - app-network
  mongo:
    image: mongo:latest
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "8000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
